disallowed-types = [
    { path = "std::sync::Mutex", reason = "avoid importing std::sync directly", replacement = "crate::sync" },
    { path = "std::sync::RwLock", reason = "avoid importing std::sync directly", replacement = "crate::sync" },
    # shuttle currently re-exports std::sync::Arc, so we cannot disallow it yet
    # { path = "std::sync::Arc", reason = "avoid importing std::sync directly", replacement = "crate::sync::Arc" },
    { path = "std::sync::RwLockReadGuard", reason = "avoid importing std::sync directly", replacement = "crate::sync::RwLockReadGuard" },
    { path = "std::sync::RwLockWriteGuard", reason = "avoid importing std::sync directly", replacement = "crate::sync::RwLockWriteGuard" },
    { path = "std::sync::MutexGuard", reason = "avoid importing std::sync directly", replacement = "crate::sync::MutexGuard" },
    { path = "std::thread::JoinHandle", reason = "avoid importing std::thread directly", replacement = "crate::thread::JoinHandle" },
    { path = "std::sync::Barrier", reason = "avoid importing std::sync directly", replacement = "crate::sync::Barrier" },
    # Atomic types
    { path = "std::sync::atomic::AtomicBool", reason = "avoid importing std::sync directly", replacement = "crate::sync::atomic::AtomicBool" },
    { path = "std::sync::atomic::AtomicIsize", reason = "avoid importing std::sync directly", replacement = "crate::sync::atomic::AtomicIsize" },
    { path = "std::sync::atomic::AtomicUsize", reason = "avoid importing std::sync directly", replacement = "crate::sync::atomic::AtomicUsize" },
    { path = "std::sync::atomic::AtomicI8", reason = "avoid importing std::sync directly", replacement = "crate::sync::atomic::AtomicI8" },
    { path = "std::sync::atomic::AtomicU8", reason = "avoid importing std::sync directly", replacement = "crate::sync::atomic::AtomicU8" },
    { path = "std::sync::atomic::AtomicI16", reason = "avoid importing std::sync directly", replacement = "crate::sync::atomic::AtomicI16" },
    { path = "std::sync::atomic::AtomicU16", reason = "avoid importing std::sync directly", replacement = "crate::sync::atomic::AtomicU16" },
    { path = "std::sync::atomic::AtomicI32", reason = "avoid importing std::sync directly", replacement = "crate::sync::atomic::AtomicI32" },
    { path = "std::sync::atomic::AtomicU32", reason = "avoid importing std::sync directly", replacement = "crate::sync::atomic::AtomicU32" },
    { path = "std::sync::atomic::AtomicI64", reason = "avoid importing std::sync directly", replacement = "crate::sync::atomic::AtomicI64" },
    { path = "std::sync::atomic::AtomicU64", reason = "avoid importing std::sync directly", replacement = "crate::sync::atomic::AtomicU64" },
]

disallowed-methods = [
    { path = "std::thread::spawn", reason = "use crate::thread::spawn instead", replacement = "crate::thread::spawn" },
    { path = "std::thread::scope", reason = "use crate::thread::scope instead", replacement = "crate::thread::scope" },
    { path = "std::thread::sleep", reason = "use crate::thread::sleep instead", replacement = "crate::thread::sleep" },
    { path = "std::hint::spin_loop", reason = "use crate::hint::spin_loop instead", replacement = "crate::hint::spin_loop" },
    { path = "std::thread::yield_now", reason = "use crate::thread::yield_now instead", replacement = "crate::thread::yield_now" },
]
